USE [Shoppinglist_app_ORM_demo];

INSERT INTO Shoppinglist_app_ORM_demo.dbo.Vendor(VendorName,Storebox,Discountclub ) 
VALUES
('Føtex', 1, 1)
('SuperBrugsen', 1, 1)
('Meny', 1, 1)
('Lidl', 1, 1)
('Normal', 1, 1)
('Matas', 1, 1)
('Ringsted Apotek', 0, 0)
('Jem & Fix', 0, 0)
('Bilka', 1, 1)
('Rema 1000', 1, 1)
('Aldi', 1, 1)
('Kvickly', 1, 1)
('Spar', 1, 1)
('Irma', 1, 1)
('Coop', 1, 1)
('Elgiganten', 0, 0)
('Power', 0, 0)
('Bauhaus', 0, 0)
('Harald Nyborg', 0, 0)
('XL-Byg', 0, 0)
('Stark', 0, 0)
('Silvan', 0, 0)
('Bog & Ide', 0, 0)
('Arnold Busck', 0, 0)
('Saxo', 0, 0)